name: Unzip Fonts

on:
  push:
    paths:
      - 'fonts.zip'  # 当 fonts.zip 文件有更新时触发工作流

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unzip fonts
        run: unzip fonts.zip -d fonts

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add fonts/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Unzip font files"
            git push
          fi
